const productos = [
  {
    id: 1,
    title: 'Cartera de noche',
    description: 'Cartera de cuero para salidas de noche',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/cartera.png",
    price: 10,
    taxes: 0.105,
    discount: 0.00,
    maxBuyQty: 2,
    stock: 2,
  },
  {
    id: 2,
    title: 'Matero Campo',
    description: 'Matero de campo metático',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/matero.png",
    price: 15,
    taxes: 0.105,
    discount: 0.0,
    maxBuyQty: 2,
    stock: 0,
  },
  {
    id: 3,
    title: 'Medias de Lycra',
    description: 'Medias de lycra by Dupont',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'woman',
    image: "/images/products/medias.png",
    price: 12,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 0,
  },
  {
    id: 4,
    title: 'Remera Junior',
    description: 'Remera de algodon para jóvenes',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'child',
    image: "/images/products/remera.png",
    price: 10,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 5,
    title: 'Taza mañanera',
    description: 'Taza mañanera naranja ',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/taza01.png",
    price: 5,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 6,
    title: 'Taza Divertida',
    description: 'Taza divertida para colorear tus mañanas ',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/taza02.png",
    price: 5,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 7,
    title: 'Taza Classic',
    description: 'Taza clásica para café',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/taza03.png",
    price: 5,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 8,
    title: 'Remera Hombre',
    description: 'Remera Hombre',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'man',
    image: "/images/products/remera_hombre.png",
    price: 10,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 0,
  },
  {
    id: 9,
    title: 'Remera Mujer',
    description: 'Remera Mujer',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'woman',
    image: "/images/products/remera_mujer.png",
    price: 10,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 10,
    title: 'Medias Niño',
    description: 'Medias Niño',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'child',
    image: "/images/products/medias_niño.jpeg",
    price: 7,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 11,
    title: 'Medias Hombre',
    description: 'Medias Hombre',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'man',
    image: "/images/products/medias_hombre.jpeg",
    price: 7,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 12,
    title: 'Botella Térmica',
    description: 'Botella Térmica',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/botella.jpeg",
    price: 9,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 13,
    title: 'Pantalón Hombre',
    description: 'Pantalón Hombre',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'man',
    image: "/images/products/pantalon_hombre.png",
    price: 12,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 2,
  },
  {
    id: 14,
    title: 'Pantalón Mujer',
    description: 'Pantalón Mujer',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'woman',
    image: "/images/products/pantalon_mujer.jpg",
    price: 12,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 15,
    title: 'Pullover Hombre',
    description: 'Pullover Hombre',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'man',
    image: "/images/products/pullover_hombre.jpeg",
    price: 13,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 16,
    title: 'Pullover Mujer',
    description: 'Pullover Mujer',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'woman',
    image: "/images/products/pullover_mujer.jpg",
    price: 13,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 17,
    title: 'Pullover Niño',
    description: 'Pullover Niño',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'child',
    image: "/images/products/pullover_niño.jpg",
    price: 10,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 18,
    title: 'Toallas',
    description: 'Toallas',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    genre:'gift',
    image: "/images/products/toallas.jpg",
    price: 8,
    taxes: 0.105,
    discount: 0.05,
    maxBuyQty: 2,
    stock: 5,
  }
]

export { productos }