const productos = [
  {
    id: 1,
    title: 'Cartera de noche',
    description: 'CArtera de cuero para salidas de noche',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/cartera.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 2,
    title: 'Matero Campo',
    description: 'Matero de campo metático',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/matero.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 3,
    title: 'Medias de Lycra',
    description: 'Medias de lycra by Dupont',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/medias.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 4,
    title: 'Remera Junior',
    description: 'Remera de algodon para jóvenes',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/remera.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 5,
    title: 'Taza mañanera',
    description: 'Taza mañanera naranja ',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/taza01.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 6,
    title: 'Taza Divertida',
    description: 'Taza divertida para colorear tus mañanas ',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/taza02.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
  {
    id: 7,
    title: 'Taza Classic',
    description: 'Taza clásica para café',
    adittionalDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    image: "/images/products/taza03.png",
    price: 200,
    maxBuyQty: 2,
    stock: 5,
  },
]

export { productos }