import { Inter , Ubuntu , Mulish , Josefin_Slab , Montserrat , Poppins , Noto_Sans , ABeeZee } from 'next/font/google'
import NavBar from "@/components/NavBar/navBar";

const ubuntu = Ubuntu({ 
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

const mainFont = ABeeZee({ 
  weight: ['400'],
    style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mainFont.className}>
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
